# Generated by Django 2.1.7 on 2019-04-07 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anvil_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=128)),
                ('job_uuid', models.UUIDField(default=uuid.uuid4)),
                ('job_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_finish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_completed', models.DateTimeField(blank=True, null=True)),
                ('job_nmap_version', models.CharField(blank=True, max_length=64)),
                ('job_scan_args', models.CharField(blank=True, max_length=128)),
                ('job_target', models.TextField(blank=True)),
                ('job_total_hosts', models.TextField(blank=True)),
                ('job_online_hosts', models.TextField(blank=True)),
                ('job_offline_hosts', models.TextField(blank=True)),
                ('job_status', models.CharField(blank=True, max_length=64)),
                ('job_stage', models.CharField(default=0, max_length=64)),
                ('job_celery_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='anvil_os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=255)),
                ('os_family', models.CharField(max_length=255)),
                ('os_generation', models.CharField(max_length=255)),
                ('os_type', models.CharField(max_length=255)),
                ('os_vendor', models.CharField(max_length=255)),
                ('os_accuracy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='anvil_port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.CharField(max_length=255)),
                ('port_protocol', models.CharField(max_length=255)),
                ('port_state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='anvil_script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_id', models.IntegerField(default=0)),
                ('script_output', models.TextField(blank=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.anvil_port')),
            ],
        ),
        migrations.CreateModel(
            name='anvil_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_product', models.CharField(max_length=255)),
                ('service_version', models.CharField(max_length=255)),
                ('service_extra', models.CharField(max_length=255)),
                ('service_fingerprint', models.CharField(max_length=255)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.anvil_port')),
            ],
        ),
        migrations.CreateModel(
            name='anvil_target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('target_checked', models.CharField(max_length=255)),
                ('target_os_match', models.CharField(max_length=255)),
                ('target_os_accuracy', models.CharField(max_length=255)),
                ('target_ip', models.CharField(max_length=255)),
                ('target_ipv4', models.CharField(max_length=255)),
                ('target_ipv6', models.CharField(max_length=255)),
                ('target_mac', models.CharField(max_length=255)),
                ('target_status', models.CharField(max_length=255)),
                ('target_hostname', models.CharField(max_length=255)),
                ('target_vendor', models.CharField(max_length=255)),
                ('target_uptime', models.CharField(max_length=255)),
                ('target_lastboot', models.CharField(max_length=255)),
                ('target_distance', models.IntegerField(default=0)),
                ('target_state', models.CharField(max_length=255)),
                ('target_count', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.anvil_job')),
                ('os', models.ManyToManyField(to='sdb.anvil_os')),
                ('port', models.ManyToManyField(to='sdb.anvil_port')),
            ],
        ),
        migrations.AddField(
            model_name='anvil_script',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.anvil_target'),
        ),
        migrations.AddField(
            model_name='anvil_port',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.anvil_target'),
        ),
        migrations.AddField(
            model_name='anvil_os',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdb.anvil_target'),
        ),
    ]
